In [30]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
df=pd.read_csv(r'/content/fake_news_dataset.csv')
print(df)

        id               title        author  \
0        1     Breaking News 1    Jane Smith
1        2     Breaking News 2   Emily Davis
2        3     Breaking News 3      John Doe
3        4     Breaking News 4  Alex Johnson
4        5     Breaking News 5   Emily Davis
...    ...                 ...           ...
3995  3996  Breaking News 3996      John Doe
3996  3997  Breaking News 3997  Alex Johnson
3997  3998  Breaking News 3998  Alex Johnson
3998  3999  Breaking News 3999      John Doe
3999  4000  Breaking News 4000      John Doe

                                                   text           state  \
0     This is the content of article 1. It contains ...       Tennessee
1     This is the content of article 2. It contains ...       Wisconsin
2     This is the content of article 3. It contains ...        Missouri
3     This is the content of article 4. It contains ...  North Carolina
4     This is the content of article 5. It contains ...      California
...                                                 ...             ...
3995  This is the content of article 3996. It contai...            Ohio
3996  This is the content of article 3997. It contai...      Washington
3997  This is the content of article 3998. It contai...      California
3998  This is the content of article 3999. It contai...        Illinois
3999  This is the content of article 4000. It contai...           Texas

     date_published          source       category  sentiment_score  \
0        30-11-2021       The Onion  Entertainment            -0.22
1        02-09-2021    The Guardian     Technology             0.92
2        13-04-2021  New York Times         Sports             0.25
3        08-03-2020             CNN         Sports             0.94
4        23-03-2022      Daily Mail     Technology            -0.01
...             ...             ...            ...              ...
3995     25-04-2020        InfoWars     Technology             0.91
3996     09-01-2022             CNN         Sports            -0.57
3997     03-03-2023       Breitbart  Entertainment            -0.17
3998     13-04-2021  New York Times         Health            -0.88
3999     20-12-2023    The Guardian         Health            -0.95

      word_count  ...  num_shares  num_comments  political_bias  \
0           1302  ...       47305           450          Center
1            322  ...       39804           530            Left
2            228  ...       45860           763          Center
3            155  ...       34222           945          Center
4            962  ...       35934           433           Right
...          ...  ...         ...           ...             ...
3995        1227  ...       38880           697           Right
3996        1296  ...        3650           925            Left
3997         522  ...       35391           577            Left
3998         169  ...       40424           201            Left
3999         465  ...       48913           279           Right

      fact_check_rating  is_satirical  trust_score source_reputation  \
0                 FALSE             1           76                 6
1                 Mixed             1            1                 5
2                 Mixed             0           57                 1
3                  TRUE             1           18                10
4                 Mixed             0           95                 6
...                 ...           ...          ...               ...
3995              Mixed             0           29                10
3996              FALSE             1           53                 3
3997              FALSE             0           22                 9
3998              FALSE             1            3                 6
3999               TRUE             1           73                 4

     clickbait_score  plagiarism_score  label
0               0.84             53.35   Fake
1               0.85             28.28   Fake
2               0.72              0.38   Fake
3               0.92             32.20   Fake
4               0.66             77.70   Real
...              ...               ...    ...
3995            0.22             95.46   Fake
3996            0.42             16.54   Fake
3997            0.50             28.51   Fake
3998            0.17             71.16   Real
3999            0.09             27.65   Real

[4000 rows x 24 columns]

In [31]:
df.head()

,id,title,author,text,state,date_published,source,category,sentiment_score,word_count,...,num_shares,num_comments,political_bias,fact_check_rating,is_satirical,trust_score,source_reputation,clickbait_score,plagiarism_score,label
0,1,Breaking News 1,Jane Smith,This is the content of article 1. It contains ...,Tennessee,30-11-2021,The Onion,Entertainment,-0.22,1302,...,47305,450,Center,FALSE,1,76,6,0.84,53.35,Fake
1,2,Breaking News 2,Emily Davis,This is the content of article 2. It contains ...,Wisconsin,02-09-2021,The Guardian,Technology,0.92,322,...,39804,530,Left,Mixed,1,1,5,0.85,28.28,Fake
2,3,Breaking News 3,John Doe,This is the content of article 3. It contains ...,Missouri,13-04-2021,New York Times,Sports,0.25,228,...,45860,763,Center,Mixed,0,57,1,0.72,0.38,Fake
3,4,Breaking News 4,Alex Johnson,This is the content of article 4. It contains ...,North Carolina,08-03-2020,CNN,Sports,0.94,155,...,34222,945,Center,TRUE,1,18,10,0.92,32.20,Fake
4,5,Breaking News 5,Emily Davis,This is the content of article 5. It contains ...,California,23-03-2022,Daily Mail,Technology,-0.01,962,...,35934,433,Right,Mixed,0,95,6,0.66,77.70,Real

In [32]:
df.tail()

,id,title,author,text,state,date_published,source,category,sentiment_score,word_count,...,num_shares,num_comments,political_bias,fact_check_rating,is_satirical,trust_score,source_reputation,clickbait_score,plagiarism_score,label
3995,3996,Breaking News 3996,John Doe,This is the content of article 3996. It contai...,Ohio,25-04-2020,InfoWars,Technology,0.91,1227,...,38880,697,Right,Mixed,0,29,10,0.22,95.46,Fake
3996,3997,Breaking News 3997,Alex Johnson,This is the content of article 3997. It contai...,Washington,09-01-2022,CNN,Sports,-0.57,1296,...,3650,925,Left,FALSE,1,53,3,0.42,16.54,Fake
3997,3998,Breaking News 3998,Alex Johnson,This is the content of article 3998. It contai...,California,03-03-2023,Breitbart,Entertainment,-0.17,522,...,35391,577,Left,FALSE,0,22,9,0.50,28.51,Fake
3998,3999,Breaking News 3999,John Doe,This is the content of article 3999. It contai...,Illinois,13-04-2021,New York Times,Health,-0.88,169,...,40424,201,Left,FALSE,1,3,6,0.17,71.16,Real
3999,4000,Breaking News 4000,John Doe,This is the content of article 4000. It contai...,Texas,20-12-2023,The Guardian,Health,-0.95,465,...,48913,279,Right,TRUE,1,73,4,0.09,27.65,Real

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 4000 non-null   int64
 1   title              4000 non-null   object
 2   author             4000 non-null   object
 3   text               4000 non-null   object
 4   state              4000 non-null   object
 5   date_published     4000 non-null   object
 6   source             4000 non-null   object
 7   category           4000 non-null   object
 8   sentiment_score    4000 non-null   float64
 9   word_count         4000 non-null   int64
 10  char_count         4000 non-null   int64
 11  has_images         4000 non-null   int64
 12  has_videos         4000 non-null   int64
 13  readability_score  4000 non-null   float64
 14  num_shares         4000 non-null   int64
 15  num_comments       4000 non-null   int64
 16  political_bias     4000 non-null   object
 17  fact_check_rating  4000 non-null   object
 18  is_satirical       4000 non-null   int64
 19  trust_score        4000 non-null   int64
 20  source_reputation  4000 non-null   int64
 21  clickbait_score    4000 non-null   float64
 22  plagiarism_score   4000 non-null   float64
 23  label              4000 non-null   object
dtypes: float64(4), int64(10), object(10)
memory usage: 750.1+ KB

In [34]:
df.describe()

,id,sentiment_score,word_count,char_count,has_images,has_videos,readability_score,num_shares,num_comments,is_satirical,trust_score,source_reputation,clickbait_score,plagiarism_score
count,4000.000000,4000.000000,4000.000000,4000.0000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.00000,4000.000000,4000.000000
mean,2000.500000,-0.000645,795.655750,4277.0680,0.49650,0.484500,54.764595,25144.596750,489.870250,0.497000,49.960750,5.54925,0.494447,50.598110
std,1154.844867,0.574768,406.373871,2186.2073,0.50005,0.499822,14.404027,14387.537467,287.435733,0.500054,29.467911,2.87422,0.289138,28.932298
min,1.000000,-1.000000,100.000000,500.0000,0.00000,0.000000,30.020000,39.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.040000
25%,1000.750000,-0.490000,445.750000,2358.7500,0.00000,0.000000,42.480000,12781.750000,238.000000,0.000000,24.000000,3.00000,0.240000,25.915000
50%,2000.500000,-0.010000,793.000000,4287.0000,0.00000,0.000000,54.235000,25308.500000,483.000000,0.000000,50.000000,6.00000,0.490000,51.480000
75%,3000.250000,0.510000,1150.000000,6206.5000,1.00000,1.000000,67.215000,37453.500000,741.000000,1.000000,76.000000,8.00000,0.740000,75.580000
max,4000.000000,1.000000,1500.000000,7996.0000,1.00000,1.000000,79.980000,50000.000000,1000.000000,1.000000,100.000000,10.00000,1.000000,99.950000

In [35]:
df.shape

(4000, 24)

In [36]:
df.isnull().sum()

id                   0
title                0
author               0
text                 0
state                0
date_published       0
source               0
category             0
sentiment_score      0
word_count           0
char_count           0
has_images           0
has_videos           0
readability_score    0
num_shares           0
num_comments         0
political_bias       0
fact_check_rating    0
is_satirical         0
trust_score          0
source_reputation    0
clickbait_score      0
plagiarism_score     0
label                0
dtype: int64

In [37]:

y=df['label']

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(max_features=5000)
x=vectorizer.fit_transform(df['text'])

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
scaler=StandardScaler(with_mean=False)
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model_lg=LogisticRegression()
model_lg.fit(x_train,y_train)

LogisticRegression()

In [46]:
y_pred=model_lg.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy of Logistic Regression:",accuracy)

Accuracy of Logistic Regression: 0.5108333333333334

In [47]:
from sklearn.svm import SVC
model_svm=SVC()
model_svm.fit(x_train,y_train)

SVC()

In [48]:
y_pred=model_svm.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy of SVM:",accuracy)

Accuracy of SVM: 0.5108333333333334

In [50]:
from sklearn.naive_bayes import GaussianNB
model_nb=GaussianNB()
model_nb.fit(x_train.toarray(),y_train)

GaussianNB()

In [52]:
y_pred=model_nb.predict(x_test.toarray())
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy of Naive Bayes:",accuracy)

Accuracy of Naive Bayes: 0.49083333333333334

In [53]:
from sklearn.ensemble import RandomForestClassifier
model_rf=RandomForestClassifier()
model_rf.fit(x_train,y_train)

RandomForestClassifier()

In [54]:
y_pred=model_rf.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy of randomforest:",accuracy)

Accuracy of randomforest: 0.5108333333333334

In [55]:
from sklearn.ensemble import GradientBoostingClassifier
model_gb=GradientBoostingClassifier()
model_gb.fit(x_train,y_train)

GradientBoostingClassifier()

In [56]:
y_pred=model_gb.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy of gradientboosting:",accuracy)

Accuracy of gradientboosting: 0.5108333333333334